name = "speedread-api"
main = "src/index.ts"
compatibility_date = "2025-01-29"

[[kv_namespaces]]
binding = "CONTENT_KV"
id = "0a32a0b8ffbc4e02950131a8e8ca854c"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "ed6d080f2a54424b87929b1c270301e7"

[vars]
ALLOWED_ORIGIN = "https://read.marx.sh"
MAX_CONTENT_SIZE = "512000"
CONTENT_TTL_SECONDS = "1800"
RATE_LIMIT_MAX = "10"
RATE_LIMIT_WINDOW_SECONDS = "60"
